package com.hudutech.blooddonorsapp.util;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.net.Uri;
import android.support.v4.app.ActivityCompat;

import java.util.HashMap;

public class Utils {

    public static void makeCall(Context context, String mobileNumber) {
        Intent intent = new Intent(Intent.ACTION_CALL);
        intent.setData(Uri.parse("tel:+" + mobileNumber));
        if (ActivityCompat.checkSelfPermission(context, android.Manifest.permission.CALL_PHONE) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            // here to request the missing permissions, and then overriding
            //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
            //                                          int[] grantResults)
            // to handle the case where the user grants the permission. See the documentation
            // for ActivityCompat#requestPermissions for more details.
            return;
        }
        context.startActivity(intent);
    }

    public static boolean isConnected(Context context) {
        ConnectivityManager connMgr = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connMgr.getActiveNetworkInfo();
        return networkInfo != null && networkInfo.isConnected();
    }

    public static void setLoggedIn(Context context) {
        SharedPreferences sharedPrefs = context.getSharedPreferences("AUTH_DATA",
                Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPrefs.edit();
        editor.putBoolean("loggedIn", true);
        editor.apply();
        editor.commit();
    }

    public static void setLoggedOut(Context context) {
        SharedPreferences sharedPrefs = context.getSharedPreferences("AUTH_DATA",
                Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPrefs.edit();
        editor.putBoolean("loggedIn", false);
        editor.apply();
        editor.commit();
    }

    public static boolean isLoggedIn(Context context) {
        SharedPreferences sharedPrefs = context.getSharedPreferences("AUTH_DATA",
                Context.MODE_PRIVATE);
        return sharedPrefs.getBoolean("loggedIn", false);
    }


    public static String[] getArrayMap() {
        return new String[]{
                "Attingal",
                "Neyyattinkara",
                "Nedumangad",
                "Varkala",
                "Karunagapally",
                "Paravoor (South)",
                "Punalur",
                "Kottarakkara",
                "Alappuzha",
                "Chengannur",
                "Cherthala",
                "Kayamkulam",
                "Mavelikkara",
                "Harippad",
                "Adoor",
                "Pathanamthitta",
                "Thiruvalla",
                "Pandalam",
                "Thodupuzha",
                "Kattappana",
                "Kottayam",
                "Palai",
                "Vaikom",
                "Changanacherry",
                "Ettumanoor",
                "Erattupetta",
                "Aluva",
                "Angamaly",
                "Kalamassery",
                "Kothamangalam",
                "Muvattupuzha",
                "North Paravoor",
                "Maradu",
                "Perumbavoor",
                "Thrikkakara",
                "Thripunithura",
                "Eloor",
                "Piravam",
                "Koothattukulam",
                "Chalakkudy",
                "Chavakkad",
                "Guruvayoor",
                "Irinjalakuda",
                "Kodungallur",
                "Kunnamkulam",
                "Vadakkancherry",
                "Ottappalam",
                "Palakkad.Shornur",
                "Chittur - Tattamangalam",
                "Pattambi",
                "Cherppulassery",
                "Mannarkkadu",
                "Malappuram",
                "Manjeri",
                "Kottakkal",
                "Nilambur",
                "Perinthalmanna",
                "Ponnani",
                "Tirur",
                "Parappanangadi",
                "Valancherry",
                "Thiroorangadi",
                "Thanoor",
                "Kondotty",
                "Koyilandy",
                "Vadakara",
                "Payyoli",
                "Mukkam",
                "Koduvally",
                "Ramanattukarae",
                "Faroke",
                "Kalpetta",
                "Mananthavady",
                "Sulthan Bathery",
                "Koothuparambu",
                "Mattannur",
                "Payyannur",
                "Thalassery",
                "Thaliparamba",
                "Anthoor",
                "Panoor",
                "Iritty",
                "Sreekantapuram",
                "Kasaragod",
                "Kanhangad",
                "Nileswaram"

        };


    }


    public static HashMap<String, String[]> initDataHashMap() {

        HashMap<String, String[]> arrayMap = new HashMap<>();
        String[] thiruvananthapuram = new String[]{
                "Attingal",
                "Neyyattinkara",
                "Nedumangad",
                "Varkala",
                "Amboori",
                "Anad",
                "Anchuthengu",
                "Andoorkonam",
                "Aruvikkara",
                "Aryanad",
                "Aryancode",
                "Athiyannoor",
                "Azhoor",
                "Balaramapuram",
                "Chemmaruthy",
                "Chenkal",
                "Cherunniyoor",
                "Chirayinkeezhu",
                "Edava",
                "Elakamon",
                "Kadakkavoor",
                "Kadinamkulam",
                "Kallara",
                "Kallikkadu",
                "Kalliyoor",
                "Kanjiramkulam",
                "Karakulam",
                "Karavaram",
                "Karode",
                "Karumkulam",
                "Kattakada",
                "Kilimanoor",
                "Kizhuvilam",
                "Kollayil",
                "Kottukal",
                "Kulathoor",
                "Kunnathukal",
                "Kuttichal",
                "Madavoor",
                "Malayinkeezh",
                "Manamboor",
                "Mangalapuram",
                "Manickal",
                "Maranalloor",
                "Mudakkal",
                "Nagaroor",
                "Nanniyode",
                "Navaikulam",
                "Nellanad",
                "Ottasekharamangalam",
                "Ottoor",
                "Pallichal",
                "Pallickal",
                "Panavoor",
                "Pangode",
                "Parassala",
                "Pazhayakunnumel",
                "Peringammala",
                "Perumkadavila",
                "Poovachal",
                "Poovar",
                "Pothencode",
                "Pulimath",
                "Pullampara",
                "Thirupuram",
                "Tholicode",
                "Uzhamalakkal",
                "Vakkom",
                "Vamanapuram",
                "Vellanad",
                "Vellarada",
                "Vembayam",
                "Venganoor",
                "Vettoor",
                "Vilappil",
                "Vilavoorkal",
                "Vithura"
        };

        arrayMap.put("thiruvananthapuram", thiruvananthapuram);

        String[] kollam = new String[]{
                "Karunagapally",
                "Paravoor(South)",
                "Punalur",
                "Kottarakkara",
                "Adichanalloor",
                "Alappad",
                "Alayamon",
                "Anchal",
                "Aryankavu",
                "Chadayamangalam",
                "Chathannoor",
                "Chavara",
                "Chirakkara",
                "Chithara",
                "Clappana",
                "East Kallada",
                "Edamulackal",
                "Elamadu",
                "Elampalloor",
                "Ezhukone",
                "Ittiva",
                "Kadakkal",
                "Kalluvathukkal",
                "Karavaloor",
                "Kareepra",
                "Kottamkara",
                "Kulakkada",
                "Kulasekharapuram",
                "Kulathupuzha",
                "Kummil",
                "Kundara",
                "Kunnathoor",
                "Mayyanad",
                "Melila",
                "Munroethuruth",
                "Mylom",
                "Mynagappally",
                "Nedumpana",
                "Neduvathoor",
                "Neendakara",
                "Nilamel",
                "Oachira",
                "Panayam",
                "Panmana",
                "Pathanapuram",
                "Pattazhi",
                "Pattazhi Vadakkekara",
                "Pavithreswaram",
                "Perayam",
                "Perinad",
                "Piravanthoor",
                "Poothakulam",
                "Pooyappally",
                "Poruvazhy",
                "Sasthamcotta",
                "Sooranad North",
                "Sooranad South",
                "Thalavoor",
                "Thazhava",
                "Thekkumbhagom",
                "Thenmala",
                "Thevalakkara",
                "Thodiyoor",
                "Thrikkaruva",
                "Thrikkovilvattom",
                "Ummannoor",
                "Velinalloor",
                "Veliyam",
                "Vettikavala",
                "Vilakkudy",
                "West Kallada",
                "Yeroor"
        };

        arrayMap.put("kollam", kollam);


        String[] alappuzha = new String[]{
                "Alappuzha",
                "Chengannur",
                "Cherthala",
                "Kayamkulam",
                "Mavelikkara",
                "Harippad",
                "Ala",
                "Ambalapuzha North",
                "Ambalapuzha South",
                "Arattupuzha",
                "Arookutty",
                "Aroor",
                "Aryad",
                "Bharanickavu",
                "Budhanoor",
                "Champakulam",
                "Chennam Pallippuram",
                "Chennithala-Thripperumthura",
                "Cheppad",
                "Cheriyanad",
                "Cherthala South",
                "Cheruthana",
                "Chettikulangara",
                "Chingoli",
                "Chunakara",
                "Devikulangara",
                "Edathua",
                "Ezhupunna",
                "Kadakkarappally",
                "Kainakary",
                "Kandalloor",
                "Kanjikuzhy",
                "Karthikappally",
                "Karuvatta",
                "Kavalam",
                "Kodamthuruth",
                "Krishnapuram",
                "Kumarapuram",
                "Kuthiathod",
                "Mannancherry",
                "Mannar",
                "Mararikulam North",
                "Mararikulam South",
                "Mavelikara Thamarakulam",
                "Mavelikara Thekkekara",
                "Muhamma",
                "Mulakuzha",
                "Muthukulam",
                "Muttar",
                "Nedumudi",
                "Neelamperoor",
                "Nooranad",
                "Palamel",
                "Pallippad",
                "Panavally",
                "Pandanad",
                "Pathiyoor",
                "Pattanakkad",
                "Perumpalam",
                "Pulincunnoo",
                "Puliyoor",
                "Punnapra North",
                "Punnapra South",
                "Purakkad",
                "Ramankary",
                "Thakazhy",
                "Thalavady",
                "Thanneermukkom",
                "Thazhakara",
                "Thiruvanvandoor",
                "Thrikkunnappuzha",
                "Thuravoor",
                "Thycattussery",
                "Vallikunnam",
                "Vayalar",
                "Veeyapuram",
                "Veliyanad",
                "Venmoney"
        };

        arrayMap.put("alappuzha", alappuzha);

        String[] pathanamthitta = new String[]{
                "Adoor",
                "Pathanamthitta",
                "Thiruvalla",
                "Pandalam",
                "Anicadu",
                "Aranmula",
                "Aruvappulam",
                "Ayroor",
                "Chenneerkara",
                "Cherukole",
                "Chittar",
                "Elanthoor",
                "Enadimangalam",
                "Erathu",
                "Eraviperoor",
                "Ezhamkulam",
                "Ezhumattoor",
                "Kadampanad",
                "Kadapra",
                "Kalanjoor",
                "Kallooppara",
                "Kaviyoor",
                "Kodumon",
                "Koipuram",
                "Konni",
                "Kottanad",
                "Kottangal",
                "Kozhencherry",
                "Kulanada",
                "Kunnamthanam",
                "Kuttoor",
                "Malayalapuzha",
                "Mallappally",
                "Mallappuzhassery",
                "Mezhuveli",
                "Mylapra",
                "Naranammoozhy",
                "Naranganam",
                "Nedumpuram",
                "Niranam",
                "Omalloor",
                "Pallickal",
                "Pandalam Thekkekara",
                "Peringara",
                "Pramadom",
                "Puramattom",
                "Ranni",
                "Ranni Angadi",
                "Ranni Pazhavangadi",
                "Ranni Perunadu",
                "Seethathodu",
                "Thannithodu",
                "Thottappuzhassery",
                "Thumpamon",
                "Vadaserikara",
                "Vallicode",
                "Vechoochira"
        };

        arrayMap.put("pathanamthitta", pathanamthitta);

        String[] idukki = new String[]{
                "Thodupuzha",
                "Kattappana",
                "Adimaly",
                "Alakode",
                "Arakulam",
                "AyyappanCoil",
                "BysonValley",
                "Chakkupallam",
                "Chinnakanal",
                "Devikulam",
                "Edamalakkudy",
                "Edavetty",
                "Elappara",
                "Erattayar",
                "IdukkiKanjikuzhy",
                "Kamakshy",
                "Kanchiyar",
                "Kanthalloor",
                "Karimannoor",
                "Karimkunnam",
                "Karunapuram",
                "Kodikulam",
                "Kokkayar",
                "Konnathady",
                "Kudayathoor",
                "Kumaramangalam",
                "Kumily",
                "Manakkad",
                "Mankulam",
                "Marayoor",
                "Mariyapuram",
                "Munnar",
                "Muttom",
                "Nedumkandam",
                "Pallivasal",
                "Pampadumpara",
                "Peermade",
                "Peruvanthanam",
                "Purapuzha",
                "Rajakkad",
                "Rajakumary",
                "Santhanpara",
                "Senapathy",
                "Udumbanchola",
                "Udumbanoor",
                "Upputhara",
                "Vandanmedu",
                "Vandiperiyar",
                "Vannappuram",
                "Vathikudy",
                "Vattavada",
                "Vazhathope",
                "Vellathooval",
                "Velliyamattom"
        };

        arrayMap.put("idukki", idukki);

        String[] kottayam = new String[]{
                "Kottayam",
                "Palai",
                "Vaikom",
                "Changanacherry",
                "Ettumanoor",
                "Erattupetta",
                "Akalakunnam",
                "Arpookara",
                "Athirampuzha",
                "Ayarkunnam",
                "Aymanam",
                "Bharananganam",
                "Chempu",
                "Chirakkadavu",
                "Elikulam",
                "Erumely",
                "Kadanad",
                "Kadaplamattom",
                "Kaduthuruthy",
                "Kallara",
                "Kanakkary",
                "Kangazha",
                "Kanjirappally",
                "Karoor",
                "Karukachal",
                "Kidangoor",
                "Kooroppada",
                "Koottickal",
                "Koruthodu",
                "Kozhuvanal",
                "Kumarakom",
                "Kuravilangad",
                "Kurichy",
                "Madappally",
                "Manarcadu",
                "Manimala",
                "Manjoor",
                "Marangattupilly",
                "Maravanthuruthu",
                "Meenachil",
                "Meenadom",
                "Melukavu",
                "Moonnilavu",
                "Mulakulam",
                "Mundakayam",
                "Mutholy",
                "Nedumkunnam",
                "Neendoor",
                "Neezhoor",
                "Paippad",
                "Pallickathodu",
                "Pampady",
                "Panachikkad",
                "Parathodu",
                "Poonjar",
                "Poonjar Thekkekara",
                "Puthuppally",
                "Ramapuram",
                "Teekoy",
                "Thalanad",
                "Thalappalam",
                "Thalayazham",
                "Thalayolaparambu",
                "Thidanad",
                "Thiruvarppu",
                "Thrickodithanam",
                "TV Puram",
                "Udayanapuram",
                "Uzhavoor",
                "Vakathanam",
                "Vazhappally",
                "Vazhoor",
                "Vechoor",
                "Veliyannoor",
                "Vellavoor",
                "Velloor",
                "Vijayapuram"
        };

        arrayMap.put("kottayam", kottayam);

        String[] ernakulam = new String[]{
                "Aluva",
                "Angamaly",
                "Kalamassery",
                "Kothamangalam",
                "Muvattupuzha",
                "North Paravoor",
                "Maradu",
                "Perumbavoor",
                "Thrikkakara",
                "Thripunithura",
                "Eloor",
                "Piravam",
                "Koothattukulam",
                "Aikaranad",
                "Alangad",
                "Amballoor",
                "Arakuzha",
                "Asamannoor",
                "Avoly",
                "Ayavana",
                "Ayyampuzha",
                "Chellanam",
                "Chendamangalam",
                "Chengamanad",
                "Cheranalloor",
                "Chittattukara",
                "Choornikkara",
                "Chottanikkara",
                "Edakkattuvayal",
                "Edathala",
                "Edavanakkad",
                "Elanji",
                "Elankunnapuzha",
                "Ezhikkara",
                "Kadamakudy",
                "Kadungalloor",
                "Kalady",
                "Kalloorkad",
                "Kanjoor",
                "Karukutty",
                "Karumallur",
                "Kavalangad",
                "Keerampara",
                "Keezhmad",
                "Kizhakkambalam",
                "Koovappady",
                "Kottappady",
                "Kottuvally",
                "Kumbalam",
                "Kumbalanghi",
                "Kunnathunad",
                "Kunnukara",
                "Kuttampuzha",
                "Kuzhuppilly",
                "MalayattoorNeeleswaram",
                "Maneed",
                "Manjalloor",
                "Manjapra",
                "Marady",
                "Mazhuvannoor",
                "Mookkannur",
                "Mudakuzha",
                "Mulanthuruthy",
                "Mulavukad",
                "Narakal",
                "Nayarambalam",
                "Nedumbassery",
                "Nellikuzhi",
                "Okkal",
                "Paingottoor",
                "Paipra",
                "Palakuzha",
                "Pallarimangalam",
                "Pallippuram",
                "Pampakuda",
                "Parakkadavu",
                "Pindimana",
                "Poothrikka",
                "Pothanicad",
                "Puthenvelikkara",
                "Ramamangalam",
                "Rayamangalam",
                "Sreemoolanagaram",
                "Thirumarady",
                "Thiruvaniyoor",
                "Thuravoor",
                "Udayamperoor",
                "Vadakkekkara",
                "VadavucodePuthencruz",
                "Valakom",
                "Varappetty",
                "Varapuzha",
                "Vazhakulam",
                "Vengola",
                "Vengoor"
        };

        arrayMap.put("ernakulam", ernakulam);

        String[] thrissur = new String[]{
                "Chalakkudy",
                "Chavakkad",
                "Guruvayoor",
                "Irinjalakuda",
                "Kodungallur",
                "Kunnamkulam",
                "Vadakkancherry",
                "Adat",
                "Alagappanagar",
                "Aloor",
                "Annamanada",
                "Anthikad",
                "Arimpur",
                "Athirappilly",
                "Avanur",
                "Avinissery",
                "Chazhur",
                "Chelakkara",
                "Cherpu",
                "Choondal",
                "Chowannur",
                "Desamangalam",
                "Edathiruthy",
                "Edavilangu",
                "Elavally",
                "Engandiyur",
                "Eriyad",
                "Erumapetty",
                "Kadangode",
                "Kadappuram",
                "Kadavallur",
                "Kadukutty",
                "Kaipamangalam",
                "Kaiparambu",
                "Kandanassery",
                "Karalam",
                "Kattakampal",
                "Kattoor",
                "Kodakara",
                "Kodassery",
                "Kolazhy",
                "Kondazhy",
                "Koratty",
                "Kuzhur",
                "Madakkathara",
                "Mala",
                "Manalur",
                "Mathilakam",
                "Mattathur",
                "Meloor",
                "Mulakunnathukavu",
                "Mullassery",
                "Mullurkara",
                "Muriyad",
                "Nadathara",
                "Nattika",
                "Nenmanikkara",
                "Orumanayur",
                "Padiyur",
                "Pananchery",
                "Panjal",
                "Paralam",
                "Parappukkara",
                "Pariyaram",
                "Pavaratty",
                "Pazhayannur",
                "Perinjanam",
                "Poomangalam",
                "Porkulam",
                "Poyya",
                "Pudukad",
                "Punnayur",
                "Punnayurkulam",
                "Puthenchira",
                "Puthur",
                "Sreenarayanapuram",
                "Thalikulam",
                "Thanniyam",
                "Thekkumkara",
                "Thiruvilwamala",
                "Tholur",
                "Thrikkur",
                "Vadakkekkad",
                "Valapad",
                "Vallachira",
                "VallatholNagar",
                "Varandarappilly",
                "Varavoor",
                "Vatanapally",
                "Vellangallur",
                "Velukara",
                "Velur",
                "Venkitangu"
        };
        arrayMap.put("thrissur", thrissur);

        String[] palakkad = new String[]{
                "Ottappalam",
                "Palakkad",
                "Shornur",
                "Chittur Tattamangalam",
                "Pattambi",
                "Cherppulassery",
                "Mannarkkadu",
                "Agali",
                "Akathethara",
                "Alanallur",
                "Alathur",
                "Ambalappara",
                "Anakkara",
                "Ananganadi",
                "Ayiloor",
                "Chalavara",
                "Chalissery",
                "Elappully",
                "Elavancherry",
                "Erimayur",
                "Eruthenpathy",
                "Kadampazhipuram",
                "Kanhirapuzha",
                "Kannadi",
                "Kannambra",
                "Kappur",
                "Karakurussi",
                "Karimba",
                "Karimpuzha",
                "Kavassery",
                "Keralassery",
                "Kizhakkencherry",
                "Kodumbu",
                "Koduvayur",
                "Kollengode",
                "Kongad",
                "Koppam",
                "Kottayi",
                "Kottopadam",
                "Kozhinjampara",
                "Kulukkallur",
                "Kumaramputhur",
                "Kuthanur",
                "Kuzhalmannam",
                "Lakkidi Perur",
                "Malampuzha",
                "Mankara",
                "Mannur",
                "Marutharode",
                "Mathur",
                "Melarcode",
                "Mundur",
                "Muthalamada",
                "Muthuthala",
                "Nagalassery",
                "Nallepilly",
                "Nellaya",
                "Nelliyampathy",
                "Nenmara",
                "Ongallur",
                "Pallassana",
                "Parali",
                "Paruthur",
                "Pattanchery",
                "Pattithara",
                "Peringottukurissi",
                "Perumatty",
                "Peruvemba",
                "Pirayiri",
                "Polpully",
                "Pookkottukavu",
                "Puducode",
                "Pudunagaram",
                "Puduppariyaram",
                "Pudur",
                "Pudusseri",
                "Sholayoor",
                "Sreekrishnapuram",
                "Tachampara",
                "Tarur",
                "Thachanattukara",
                "Thenkara",
                "Thenkurissi",
                "Thirumittacode",
                "Thiruvegappura",
                "Trikkaderi",
                "Trithala",
                "Vadakarapathy",
                "Vadakkencheri",
                "Vadavannur",
                "Vallapuzha",
                "Vandazhy",
                "Vaniamkulam",
                "Vellinezhi",
                "Vilayur"
        };

        arrayMap.put("palakkad", palakkad);

        String[] malappuram = new String[]{
                "Malappuram",
                "Manjeri",
                "Kottakkal",
                "Nilambur",
                "Perinthalmanna",
                "Ponnani",
                "Tirur",
                "Parappanangadi",
                "Valanchery",
                "Thiroorangadi",
                "Thanoor",
                "Kondotty",
                "Alamkode",
                "Aliparamba",
                "Amarambalam",
                "Anakkayam",
                "Angadippuram",
                "Areacode",
                "ARNagar",
                "Athavanad",
                "Chaliyar",
                "Cheacode",
                "Chelembra",
                "Cheriyamundam",
                "Cherukavu",
                "Chokkad",
                "Chungathara",
                "Edakkara",
                "Edapal",
                "Edappatta",
                "Edarikode",
                "Edavanna",
                "Edayur",
                "Elamkulam",
                "Irimbiliyam",
                "Kaladi",
                "Kalikavu",
                "Kalpakanchery",
                "Kannamangalam",
                "Karulai",
                "Karuvarakundu",
                "Kavanur",
                "Keezhattur",
                "Keezhuparamba",
                "Kodur",
                "Koottilangadi",
                "Kuruva",
                "Kuttippuram",
                "Kuzhimanna",
                "Makkaraparamba",
                "Mampad",
                "Mangalam",
                "Mankada",
                "Marakkara",
                "Maranchery",
                "Melattur",
                "Moonniyur",
                "Moorkkanad",
                "Moothedam",
                "Morayur",
                "Muthuvalloor",
                "Nannambra",
                "Nannammukku",
                "Niramaruthur",
                "Oorakam",
                "Othukkungal",
                "Ozhur",
                "Pallikkal",
                "Pandikkad",
                "Parappur",
                "Perumanna Klari",
                "Perumpadappa",
                "Peruvalloor",
                "Ponmala",
                "Ponmundam",
                "Pookkottur",
                "Porur",
                "Pothukallu",
                "Pulamanthol",
                "Pulikkal",
                "Pulpatta",
                "Purathur",
                "Puzhakkattiri",
                "Tanalur",
                "Tavanur",
                "Thalakkad",
                "Thazhekkode",
                "Thenhipalam",
                "Thennala",
                "Thirunavaya",
                "Thiruvali",
                "Thrikkalangodu",
                "Triprangode",
                "Thuvvur",
                "Urangattiri",
                "Valavannur",
                "Vallikkunnu",
                "Vattamkulam",
                "Vazhakkad",
                "Vazhayur",
                "Vazhikkadavu",
                "Veliancode",
                "Vengara",
                "Vettathur",
                "Vettom",
                "Wandoor"
        };

        arrayMap.put("malappuram", malappuram);

        String[] kozhikkodu = new String[]{
                "Koyilandy",
                "Vadakara",
                "Payyoli",
                "Mukkam",
                "Koduvally",
                "Ramanattukara",
                "Faroke",
                "Arikkulam",
                "Atholi",
                "Ayancheri",
                "Azhiyur",
                "Balussery",
                "Chakkittapara",
                "Changaroth",
                "Chathamangalam",
                "Chekkiad",
                "Chelannur",
                "Chemanchery",
                "Chengottukavu",
                "Cheruvannur",
                "Chorode",
                "Edacheri",
                "Eramala",
                "Kadalundi",
                "Kakkodi",
                "Kakkur",
                "Karassery",
                "Kattippara",
                "Kavilumpara",
                "Kayakkody",
                "Kayanna",
                "Keezhariyur",
                "Kizhakkoth",
                "Kodanchery",
                "Kodiyathur",
                "Koodaranhi",
                "Koorachundu",
                "Koothali",
                "Kottur",
                "Kunnamangalam",
                "Kunnummal",
                "Kuruvattoor",
                "Kuttiadi",
                "Madavoor",
                "Maniyur",
                "Maruthonkara",
                "Mavoor",
                "Meppayur",
                "Moodadi",
                "Nadapuram",
                "Naduvannur",
                "Nanminda",
                "Narikunni",
                "Narippatta",
                "Nochad",
                "Olavanna",
                "Omassery",
                "Onchiyam",
                "Panangad",
                "Perambra",
                "Perumanna",
                "Peruvayal",
                "Puduppady",
                "Purameri",
                "Thalakulathur",
                "Thamarassery",
                "Thikkodi",
                "Thiruvallur",
                "Thiruvambadi",
                "Thurayur",
                "Thuneri",
                "Ulliyeri",
                "Unnikulum",
                "Valayam",
                "Vanimal",
                "Velom",
                "Villiappally"
        };

        arrayMap.put("kozhikkodu", kozhikkodu);

        String[] wayanad = {
                "Kalpetta",
                "Mananthavady",
                "Sulthan Bathery",
                "Ambalavayal",
                "Edavaka",
                "Kaniyambetta",
                "Kottathara",
                "Meenangadi",
                "Meppadi",
                "Mullankolly",
                "Muppainad",
                "Muttil",
                "Nenmeni",
                "Noolpuzha",
                "Padinharathara",
                "Panamaram",
                "Poothadi",
                "Pozhuthana",
                "Pulpally",
                "Thariode",
                "Thavinhal",
                "Thirunelly",
                "Thondernad",
                "Vellamunda",
                "Vengappally",
                "Vythiri"
        };

        arrayMap.put("wayanad", wayanad);

        String[] kannur = new String[]{
                "Koothuparamb",
                "Mattannur",
                "Payyannur",
                "Thalassery",
                "Thaliparamba",
                "Anthoor",
                "Panoor",
                "Iritty",
                "Sreekantapuram",
                "Alakode",
                "Anjarakandy",
                "Aralam",
                "Ayyankunnu",
                "Azhikode",
                "Chapparapadava",
                "Chembilode",
                "Chengalayi",
                "Cherukunnu",
                "Cherupuzha",
                "Cheruthazham",
                "Chirakkal",
                "Chittariparamba",
                "Chokli",
                "Dharmadam",
                "Eramam Kuttur",
                "Eranholi",
                "Eruvessy",
                "Ezhome",
                "Irikkur",
                "Kadambur",
                "Kadannappally Panapuzha",
                "Kadirur",
                "Kalliasseri",
                "Kanichar",
                "Kankol Alappadamba",
                "Kannapuram",
                "Karivellur Peralam",
                "Keezhallur",
                "Kelakam",
                "Kolachery",
                "Kolayad",
                "Koodali",
                "Kottayam",
                "Kottiyoor",
                "Kunhimangalam",
                "Kunnothuparamba",
                "Kurumathur",
                "Kuttiattoor",
                "Madayi",
                "Malappattam",
                "Malur",
                "Mangattidam",
                "Mattool",
                "Mayyil",
                "Mokeri",
                "Munderi",
                "Muzhakkunnu",
                "Muzhappilangad",
                "Naduvil",
                "Narath",
                "New Mahe",
                "Padiyoor",
                "Panniyannur",
                "Pappinisseri",
                "Pariyaram",
                "Pattiam",
                "Pattuvam",
                "Payam",
                "Payyavoor",
                "Peralassery",
                "Peravoor",
                "Peringome Vayakkara",
                "Pinarayi",
                "Ramanthali",
                "Thillankery",
                "Triprangottoor",
                "Udayagiri",
                "Ulikkal",
                "Valapattanam",
                "Vengad"
        };

        arrayMap.put("kannur", kannur);


        String[] kasaragod = new String[]{
                "Kasaragod",
                "Kanhangad",
                "Nileswaram",
                "Ajanur",
                "Badiadka",
                "Balal",
                "Bedadka",
                "Belloor",
                "Chemnad",
                "Chengala",
                "Cheruvathur",
                "Delampady",
                "East Eleri",
                "Enmakaje",
                "Kallar",
                "Karadka",
                "Kayyur Cheemeni",
                "Kinanoor Karinthalam",
                "KodomBelur",
                "Kumbadaje",
                "Kumbla",
                "Kuttikol",
                "Madhur",
                "Madikai",
                "Mangalpady",
                "Manjeshwar",
                "Meenja",
                "MogralPuthur",
                "Muliyar",
                "Padne",
                "Paivalike",
                "Pallikere",
                "Panathady",
                "Pilicode",
                "PullurPeriya",
                "Puthige",
                "Trikaripur",
                "Udma",
                "Valiyaparamba",
                "Vorkady",
                "West Eleri"
        };

        arrayMap.put("kasaragod", kasaragod);

        return arrayMap;


    }
}
